### ISSUE TITLE
Station component length wrong when saving mseed file using mkmseed?

### ISSUE THREAD

**Issue by taquart** [IPGP/mseed-matlab#2]
Isn't it that the station component field is 3 characters length?

I had problems reading MSEED files using rdmseed that were created with mkmseed. I noted that in line 146 of mkmseed there is:

`X.ChannelIdentifier = sprintf('%-3s',cc{4}(1:min(length(cc{4}),4)));`

After changing the last variable to 3:

`X.ChannelIdentifier = sprintf('%-3s',cc{4}(1:min(length(cc{4}),3)));`

I could successfully read the file I created when using the [X,I] = rdseed(...) option

**Comment by beaudu** [comment]
Thanks very much Grzegorz.
François.
