### ISSUE TITLE
unable to produce mseed file using mkmseed program

### ISSUE THREAD

**Issue by Akumarres** [IPGP/mseed-matlab#4]
I have one hour of 24 files for a day. I am trying to make one mseed file using 24 hourly files. But I am getting the error and my loop is stopped.

Unrecognized function or variable 'dt'.
Error in mkmseed (line 228)
	m = [0;(dt > (1 + fs_tol)/H(1).SampleRate/86400 | dt < (1 - fs_tol)/H(1).SampleRate/86400)];

I need your suggestion to resolve the issue. 

In order to avoid this issue I have used "try" and "catch" command to avoid the error.
Using these command avoid making continuous mseed files. It is like 1, 2, 5, 7, 10, 13, 15th day etc. It shows that there might be issue with the hourly mseed files. So, using "try" and "catch" is not appropriate here. 

On this ground, can we resolve the issue associated with mkmseed.m files. 

Kind Regards

**Comment by beaudu** [comment]
Can you please give more information about the context of this error ? You might contact me by email if necessary.

**Comment by beaudu** [comment]
To merge multiple miniseed files into one you just need to concatenate them using command system in a terminal. Example if your files are named file1, file2, ... :

_a. Under Linux/Mac_
`cat file* > onefile`

_b. Under Windows_
`copy /b file* onefile`

It is also possible to use `rdmseed` and `mkmseed` functions but it is interesting only if you want to select/extract specific channels in multiplex files, or change the encoding, or the data block size...
